INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (1, 'Fromage', 'Fromage de chèvre', 'nourriture');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (2, 'Huile moteur', 'Huile moteur 5W30', 'automobile');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (3, 'Crayon', 'Crayon pour dessiner et écrire.', 'fournitures');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (4, 'Jambon', 'Jambon supérieur 100% pur porc sans couenne', 'nourriture');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (5, 'Papier toilette', 'Papier toilette trois couche', 'fournitures');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (6, 'Pneu', 'Pneu 205/55 R16', 'automobile');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (7, 'Mazda RX7', 'Mazda RX7 fd3s body kit', 'automobile');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (8, 'Stylo', 'Stylo bille bleu', 'fournitures');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (9, 'Ordinateur portable', 'Ordinateur portable 15 pouces', 'électronique');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (10, 'Table', 'Table en bois massif', 'meubles');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (11, 'Chaise', 'Chaise ergonomique', 'meubles');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (654, 'Carte Pokémon', 'Cette carte Pokémon est une édition spéciale avec des caractéristiques uniques. Elle présente un design holographique avec des détails complexes et des couleurs vives. La carte inclut des informations sur les attaques, les points de vie, et les capacités ', 'cartes');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (12, 'Clavier', 'Clavier mécanique avec rétroéclairage RGB', 'électronique');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (13, 'Chaussures de sport', 'Chaussures de sport pour la course à pied', 'vêtements');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (14, 'Livre', 'Livre de science-fiction', 'livres');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (15, 'Tablette', 'Tablette tactile 10 pouces', 'électronique');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (16, 'Canapé', 'Canapé en cuir trois places', 'meubles');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (17, 'Montre', 'Montre connectée avec suivi de la santé', 'électronique');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (18, 'Jeu de société', 'Jeu de société pour toute la famille', 'loisirs');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (19, 'Parfum', 'Parfum pour homme 50ml', 'cosmétiques');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (20, 'Machine à café', 'Machine à café expresso', 'électroménager');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (21, 'Smartphone', 'Smartphone avec écran AMOLED 6.5 pouces', 'électronique');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (22, 'Imprimante', 'Imprimante multifonction jet d''encre', 'électronique');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (23, 'Chaise de bureau', 'Chaise de bureau ergonomique', 'meubles');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (24, 'Table de chevet', 'Table de chevet en bois', 'meubles');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (25, 'Enceinte Bluetooth', 'Enceinte Bluetooth portable', 'électronique');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (26, 'Appareil photo', 'Appareil photo reflex numérique', 'électronique');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (27, 'Jeans', 'Jeans slim fit', 'vêtements');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (28, 'Pull', 'Pull en laine', 'vêtements');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (29, 'Écouteurs', 'Écouteurs sans fil avec réduction de bruit', 'électronique');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (30, 'Four à micro-ondes', 'Four à micro-ondes avec grill', 'électroménager');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (31, 'Pain', 'Pain frais ', 'nourriture');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (32, 'Poulet', 'Poulet fermier', 'nourriture');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (33, 'Burger', 'Burger végétarien', 'nourriture');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (34, 'Pizza', 'Pizza 4 fromages', 'nourriture');
INSERT INTO public.produit (id_produit, nom, description, categorie) VALUES (35, 'Salade', 'Salade verte bio', 'nourriture');
